### PR TITLE
build minizip 1.2

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
*  Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Attempting to address the needs of conda-forge/libkml-feedstock#2

### CODE REVIEW

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
Well phoey, I now am getting `minizip.dll` instead of `libminizip.dll`, hmmmm

**Comment by h-vetinari** [comment]
> Well phoey, I now am getting `minizip.dll` instead of `libminizip.dll`, hmmmm

The naming doesn't have to coincide across major versions. Though as I mentioned in the libkml issue, we'll have to add static builds in addition to the shared ones, because we cannot use the shared ones (due to collision with anything depending on newer minizip)

**Comment by akrherz** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
@h-vetinari Thanks, but I am not following the static build comment.  Do you mean here within minizip or within libkml or both :)

**Comment by akrherz** [comment]
Whelp, hopefully the windows build will go green and build shared and static build libs.  If so, will apply to linux/osx too.  Shrug.

**Pull request merged**
